config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :messages
  end
  resources :messages
  filter :pagination, :uuid
  filter :locale
  get 'switch_user', to: 'switch_user#set_current_user'
  get 'switch_user/remember_user', to: 'switch_user#remember_user'
  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => '/cable'
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
  root :to => 'records#show', id: '1'
  get 'sheet/search'
  get 'sitemap' => 'sheet#sitemap', format: :xml, as: :sitemap
  get 'robots' => 'sheet#robots', format: :text
  get 'feeds', to: 'sheet#feeds', format: 'rss'
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  get 'admin/record_types/:id/fields' => 'admin/record_types#fields', as: 'admin_record_type_fields'
  get 'admin/records/:id/taxonomypage' => 'admin/records#taxonomypage', as: 'admin_records_taxonomypage'
  get 'admin/records/:id/relationpage' => 'admin/records#relationpage', as: 'admin_records_relationpage'
  get 'admin/blocks/:id/relationpage' => 'admin/blocks#relationpage', as: 'admin_blocks_relationpage'
  get 'admin/taxonomies/list/:record_type_id' => 'admin/taxonomies#list', as: 'admin_taxonomies_list'
  get 'admin/records/list/:record_type_id' => 'admin/records#list', as: 'admin_records_list'
  get 'admin/comments/list/:record_type_id' => 'admin/comments#list', as: 'admin_comments_list'
  get 'admin/transforms/list/:record_type_id' => 'admin/transforms#list', as: 'admin_transforms_list'
  get 'admin/dashboard' => 'admin/statics#dashboard', as: 'admin_dashboard'
  get 'welcome' => 'records/1'
  resources :chat_rooms, only: [:new, :create, :show, :index]

  resources :users, except: [:index]
  resources :profiles
  resources :transforms, only: [:create, :show]
  resources :comments
  resources :flags, only: [:create, :destroy, :index]
  resources :cells
 # resources :records
  resources :users do
    post :unlock, :on => :member
  end

  namespace :admin do
    resources :model_relations
    resources :plugin_managers
    resources :style_images
    resources :fci_dates
    resources :fci_images
    resources :fci_booleans
    resources :fci_decimals
    resources :fci_texts
    resources :fci_strings
    resources :fci_references
    resources :fci_full_texts
    resources :fci_files
    resources :fci_integers
    resources :fci_ratings
    resources :fcis do
      put :sort, on: :collection
    end
    resources :field_customs
    resources :records do
      resources :seomores
    end
    resources :record_types
    resources :taxonomies do
      post :sort, on: :collection
    end
    resources :systems
    resources :seomores
    resources :roles
    resources :users
    resources :menu_items do
      post :sort, on: :collection
    end
    resources :menus
    resources :blocks do
      post :sort, on: :collection
    end
    resources :permissions
    resources :profiles
    resources :cells
    resources :comments
    resources :transforms
    resources :users_roles
    resources :filter_groups
    resources :flags

  end
  #end
  DynamicRouter.load
  #get '*path', to: redirect("/#{I18n.locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.locale}/" }
  #get '', to: redirect("/#{I18n.locale}")


end

app/models/style_image.rb
class StyleImage < ApplicationRecord
  after_save :recreate_style

  def recreate_style
    FciImage.all.each do |image|
      image.value.recreate_versions!(self.machine_name.to_sym) if image.value?
    end
  end
end

app/controllers/admin/style_images_controller.rb
class Admin::StyleImagesController < Admin::BaseController
  before_action :set_style_image, only: [:show, :edit, :update, :destroy]
  layout 'admin'
  load_and_authorize_resource
  # GET /admin/style_images
  # GET /admin/style_images.json
  def index
    @style_images = StyleImage.all
  end

  # GET /admin/style_images/1
  # GET /admin/style_images/1.json
  def show
  end

  # GET /admin/style_images/new
  def new
    @style_image = StyleImage.new
  end

  # GET /admin/style_images/1/edit
  def edit
  end

  # POST /admin/style_images
  # POST /admin/style_images.json
  def create
    @style_image = StyleImage.new(style_image_params)

    respond_to do |format|
      if @style_image.save
        format.html { redirect_to [:admin, @style_image], notice: 'Style image was successfully created.' }
        format.json { render action: 'show', status: :created, location: @style_image }
      else
        format.html { render action: 'new' }
        format.json { render json: @style_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/style_images/1
  # PATCH/PUT /admin/style_images/1.json
  def update
    respond_to do |format|
      if @style_image.update(style_image_params)
        format.html { redirect_to [:admin, @style_image], notice: 'Style image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @style_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/style_images/1
  # DELETE /admin/style_images/1.json
  def destroy
    @style_image.destroy
    respond_to do |format|
      format.html { redirect_to admin_style_images_url, notice: 'Style image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_style_image
    @style_image = StyleImage.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def style_image_params
    params.require(:style_image).permit(:name, :machine_name, :process, :widht, :height, :percent)
  end
end

app/helpers/admin/style_images_helper.rb
module Admin::StyleImagesHelper
end

app/views/admin/style_images/_form.html.erb
<%= form_for([:admin, @style_image]) do |f| %>
    <% if @style_image.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@style_image.errors.count, "error") %> prohibited this style_image from being saved:</h2>

          <ul>
            <% @style_image.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :machine_name %><br>
      <%= f.text_field :machine_name %>
    </div>
    <div class="field">
      <%= f.label :process %><br>
      <%= f.text_field :process %>
    </div>
    <div class="field">
      <%= f.label :widht %><br>
      <%= f.number_field :widht %>
    </div>
    <div class="field">
      <%= f.label :height %><br>
      <%= f.number_field :height %>
    </div>
    <div class="field">
      <%= f.label :percent %><br>
      <%= f.check_box :percent %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/admin/style_images/edit.html.erb
<h1>Editing style_image</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @style_image] %> |
<%= link_to 'Back', admin_style_images_path %>

app/views/admin/style_images/index.html.erb
<h1>Listing style_images</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Machine name</th>
    <th>Process</th>
    <th>Widht</th>
    <th>Height</th>
    <th>Percent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @style_images.each do |style_image| %>
      <tr>
        <td><%= style_image.name %></td>
        <td><%= style_image.machine_name %></td>
        <td><%= style_image.process %></td>
        <td><%= style_image.widht %></td>
        <td><%= style_image.height %></td>
        <td><%= style_image.percent %></td>
        <td><%= link_to 'Show', [:admin, style_image] %></td>
        <td><%= link_to 'Edit', edit_admin_style_image_path(style_image) %></td>
        <td><%= link_to 'Destroy', [:admin, style_image], method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Style image', new_admin_style_image_path %>

app/views/admin/style_images/new.html.erb
<h1>New style_image</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_style_images_path %>

app/views/admin/style_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @style_image.name %>
</p>

<p>
  <strong>Machine name:</strong>
  <%= @style_image.machine_name %>
</p>

<p>
  <strong>Process:</strong>
  <%= @style_image.process %>
</p>

<p>
  <strong>Widht:</strong>
  <%= @style_image.widht %>
</p>

<p>
  <strong>Height:</strong>
  <%= @style_image.height %>
</p>

<p>
  <strong>Percent:</strong>
  <%= @style_image.percent %>
</p>

<%= link_to 'Edit', edit_admin_style_image_path(@style_image) %> |
<%= link_to 'Back', admin_style_images_path %>