config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :messages
  end
  resources :messages
  filter :pagination, :uuid
  filter :locale
  get 'switch_user', to: 'switch_user#set_current_user'
  get 'switch_user/remember_user', to: 'switch_user#remember_user'
  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => '/cable'
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
  root :to => 'records#show', id: '1'
  get 'sheet/search'
  get 'sitemap' => 'sheet#sitemap', format: :xml, as: :sitemap
  get 'robots' => 'sheet#robots', format: :text
  get 'feeds', to: 'sheet#feeds', format: 'rss'
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  get 'admin/record_types/:id/fields' => 'admin/record_types#fields', as: 'admin_record_type_fields'
  get 'admin/records/:id/taxonomypage' => 'admin/records#taxonomypage', as: 'admin_records_taxonomypage'
  get 'admin/records/:id/relationpage' => 'admin/records#relationpage', as: 'admin_records_relationpage'
  get 'admin/blocks/:id/relationpage' => 'admin/blocks#relationpage', as: 'admin_blocks_relationpage'
  get 'admin/taxonomies/list/:record_type_id' => 'admin/taxonomies#list', as: 'admin_taxonomies_list'
  get 'admin/records/list/:record_type_id' => 'admin/records#list', as: 'admin_records_list'
  get 'admin/comments/list/:record_type_id' => 'admin/comments#list', as: 'admin_comments_list'
  get 'admin/transforms/list/:record_type_id' => 'admin/transforms#list', as: 'admin_transforms_list'
  get 'admin/dashboard' => 'admin/statics#dashboard', as: 'admin_dashboard'
  get 'welcome' => 'records/1'
  resources :chat_rooms, only: [:new, :create, :show, :index]

  resources :users, except: [:index]
  resources :profiles
  resources :transforms, only: [:create, :show]
  resources :comments
  resources :flags, only: [:create, :destroy, :index]
  resources :cells
 # resources :records
  resources :users do
    post :unlock, :on => :member
  end

  namespace :admin do
    resources :model_relations
    resources :plugin_managers
    resources :style_images
    resources :fci_dates
    resources :fci_images
    resources :fci_booleans
    resources :fci_decimals
    resources :fci_texts
    resources :fci_strings
    resources :fci_references
    resources :fci_full_texts
    resources :fci_files
    resources :fci_integers
    resources :fci_ratings
    resources :fcis do
      put :sort, on: :collection
    end
    resources :field_customs
    resources :records do
      resources :seomores
    end
    resources :record_types
    resources :taxonomies do
      post :sort, on: :collection
    end
    resources :systems
    resources :seomores
    resources :roles
    resources :users
    resources :menu_items do
      post :sort, on: :collection
    end
    resources :menus
    resources :blocks do
      post :sort, on: :collection
    end
    resources :permissions
    resources :profiles
    resources :cells
    resources :comments
    resources :transforms
    resources :users_roles
    resources :filter_groups
    resources :flags

  end
  #end
  DynamicRouter.load
  #get '*path', to: redirect("/#{I18n.locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.locale}/" }
  #get '', to: redirect("/#{I18n.locale}")


end

app/models/taxonomy.rb
class Taxonomy < ApplicationRecord
  has_ancestry cache_depth: true
  belongs_to :record_type
  belongs_to :seomore, touch: true
  has_many :fcis, through: :record_type
  RecordType.where(model: 'Taxonomy').each do |rt|
    rt.fcis.includes(:field_custom).each do |fci|
      has_many fci.machine_name.pluralize.to_sym, -> { where(model: 'Taxonomy', fci_id: fci.id) }, :foreign_key => 'mid', class_name: fci.field_custom.machine_name.singularize.camelize
    end
  end
  has_many :model_relations, -> { where model_main: 'Taxonomy' }, :foreign_key => 'mid_main', dependent: :destroy
  has_many :reverse_model_relations, -> { where model: 'Taxonomy' }, :foreign_key => 'mid', class_name: "ModelRelation", dependent: :destroy
  has_many :records, through: :reverse_model_relations
  extend FriendlyId
  friendly_id :url, :use => [:finders]
  translates :url, :fallbacks_for_empty_translations => true

  paginates_per 20
  default_scope { order("position ASC") }
  before_save :set_entity

  def set_entity
    unless self.record_type_id.nil?
      if self.entity.nil?
        self.entity = self.record_type.machine_name
      end
    end
  end

  def title
    type = self.record_type
    if type.has_title?
      fci = type.fcis.find_by(mid: type.id, name: type.label_title)
      label=FciString.find_by(mid: self.id, model: 'Taxonomy', fci_id: fci.id)
      label.value unless label.nil?
    end
  end

  private

  def ransackable_scopes
    %w(title)
  end

end

app/controllers/admin/taxonomies_controller.rb
class Admin::TaxonomiesController < Admin::BaseController
  skip_before_filter :verify_authenticity_token
  before_action :set_taxonomy, only: [:show, :edit, :update, :destroy]
  layout 'admin'
  respond_to :html, :json
  load_and_authorize_resource
  # GET /admin/taxonomies
  # GET /admin/taxonomies.json
  def index
    @record_type_taxonomies = RecordType.where(disabled: false, model: 'Taxonomy')
     breadcrumbs.add t('listing taxonomies'), admin_taxonomies_url
  end

  # GET /admin/taxonomies/1
  # GET /admin/taxonomies/1.json
  def show
    @search = RecordType.search(params[:q])
    @types = @search.result.page params[:page]
    @mr=ModelRelation.new
    @cell= Cell.new
  end

  def list
    @taxonomy = Taxonomy.new
    @record_type = RecordType.find_by(model: 'Taxonomy', id: params[:record_type_id])
    @taxonomies = Taxonomy.where(record_type_id: params[:record_type_id]).roots.page params[:page]
    breadcrumbs.add t('listing taxonomies'), admin_taxonomies_url
    breadcrumbs.add @record_type.name
  end

  # GET /admin/taxonomies/new
  def new
    @taxonomy = Taxonomy.new
  end

  # GET /admin/taxonomies/1/edit
  def edit
    breadcrumbs.add t('listing taxonomies'), admin_taxonomies_url
    breadcrumbs.add @taxonomy.record_type.name, admin_taxonomies_list_url(@taxonomy.record_type_id)
    breadcrumbs.add @taxonomy.title
  end

  # POST /admin/taxonomies
  # POST /admin/taxonomies.json
  def create
    @taxonomy = Taxonomy.new(taxonomy_params)

    respond_to do |format|
      if @taxonomy.save
        @seomore=Seomore.create
        @taxonomy.update(seomore_id: @seomore.id)
        instance_saver(@taxonomy, params)
        format.html { redirect_to admin_taxonomies_list_path(@taxonomy.record_type_id), :gflash => {:success => t('created taxonomy item')} }
        format.json { render action: 'show', status: :created, location: @taxonomy }
      else
        format.html { render action: 'new' }
        format.json { render json: @taxonomy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/taxonomies/1
  # PATCH/PUT /admin/taxonomies/1.json
  def update
    respond_to do |format|
      if @taxonomy.update(taxonomy_params)
        instance_saver(@taxonomy, params)
        format.html { redirect_to admin_taxonomies_list_path(@taxonomy.record_type_id), :gflash => {:success => t('updated taxonomy item')} }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @taxonomy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/taxonomies/1
  # DELETE /admin/taxonomies/1.json
  def destroy
    @taxonomy.destroy
    respond_to do |format|
      format.html { redirect_to admin_taxonomies_list_path(@taxonomy.record_type_id), :gflash => {:success => t('deleted taxonomy item')} }
      format.json { head :no_content }
    end
  end

  def sort
    params[:taxonomy].sort { |a, b| a <=> b }.each_with_index do |id, index|
      value = id[1][:id].to_i
      position = id[1][:position]
      position = position.to_i + 1
      parent = id[1][:parent_id] == 'null' ? '' : id[1][:parent_id]
      Taxonomy.find(value).update_attributes(:position => position, :parent_id => parent)
    end
    render :nothing => true
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_taxonomy
    @taxonomy = Taxonomy.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def taxonomy_params
    params.require(:taxonomy).permit(:public, :blocked, :url, :taxonomy_id, :position, :record_type_id, :parent_id)
  end
end

app/controllers/taxonomies_controller.rb
class TaxonomiesController < ApplicationController
  before_action :set_taxonomy, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  respond_to :html, :json, :js
  include ApplicationHelper
  # GET /taxonomies
  # GET /taxonomies.json
  def index
    @taxonomies = Taxonomy.all
    @records = Record.all
    @search = ModelRelation.where(record_type: :product_category).search(params[:q])
    @products = @search.result
  end

  # GET /taxonomies/1
  # GET /taxonomies/1.json
  def show
    @tax = @taxonomy.records.where(public: true).search(params[:q])
    @lists = @tax.result.uniq.page(params[:page])
    breadcrumbs.add t('home'), root_url
    parent = @taxonomy.ancestors
    unless parent.nil?
      parent.each do |tax|
        breadcrumbs.add tax.title, model_url(tax)
      end
    end
    breadcrumbs.add @taxonomy.title
  end

  # GET /taxonomies/new
  def new
    @taxonomy = Taxonomy.new

  end

  # GET /taxonomies/1/edit
  def edit
  end

  # POST /taxonomies
  # POST /taxonomies.json
  def create
    @taxonomy = Taxonomy.new(taxonomy_params)

    respond_to do |format|
      if @taxonomy.save
        format.html { redirect_to @taxonomy, notice: 'Taxonomy was successfully created.' }
        format.json { render :show, status: :created, location: @taxonomy }
      else
        format.html { render :new }
        format.json { render json: @taxonomy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taxonomies/1
  # PATCH/PUT /taxonomies/1.json
  def update
    respond_to do |format|
      if @taxonomy.update(taxonomy_params)
        format.html { redirect_to @taxonomy, notice: 'Taxonomy was successfully updated.' }
        format.json { render :show, status: :ok, location: @taxonomy }
      else
        format.html { render :edit }
        format.json { render json: @taxonomy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taxonomies/1
  # DELETE /taxonomies/1.json
  def destroy
    @taxonomy.destroy
    respond_to do |format|
      format.html { redirect_to taxonomies_url, notice: 'Taxonomy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_taxonomy
    @taxonomy = Taxonomy.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def taxonomy_params
    params.require(:taxonomy).permit(:public, :blocked, :url, :taxonomy_id, :position, :record_type_id)
  end
end

app/helpers/admin/taxonomies_helper.rb
module Admin::TaxonomiesHelper
end

app/helpers/taxonomies_helper.rb
module TaxonomiesHelper

	def taxonomies_list(entity)
		Taxonomy.where(public: true, entity: entity)
	end

	def taxonomies_root(entity)
		Taxonomy.where(public: true, entity: entity).roots
	end

	def taxonomies_root_paginator(entity)
		Taxonomy.where(public: true, entity: entity).roots.page params[:page]
	end

	def taxonomies_root_paginator_ransack(entity)
		Taxonomy.where(public: true, entity: entity).roots.ransack(kartinkas_value_present: 1).result.page params[:page]
	end

	def taxonomies_child(taxonomy)
		taxonomy.children.where(public: true)
	end

end

app/views/admin/taxonomies/_current_sidebar.html.erb
<%= content_for :current_sidebar do %>
    <% @seomore= @taxonomy.seomore %>
    <h2> Seo setting</h2>
    <%= form_for([:admin, @seomore], html: {class: 'form-horizontal seomore'}) do |f| %>
        <% if @seomore.errors.any? %>
            <div id="error_explanation" class="panel panel-danger">
              <div class="panel-heading">
                <h2 class="panel-title"><%= pluralize(@seomore.errors.count, "error") %> prohibited this seomore from
                  being
                  saved:</h2>
              </div>
              <div class="panel-body">
                <ul>
                  <% @seomore.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            </div>
        <% end %>

        <div class="form-group">
          <%= f.label :title, class: 'control-label col-md-2' %>
          <div class="col-md-10">
            <%= f.text_field :title, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :keywords, class: 'control-label col-md-2' %>
          <div class="col-md-10">
            <%= f.text_field :keywords, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :desc, class: 'control-label col-md-2' %>
          <div class="col-md-10">
            <%= f.text_area :desc, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.label :noindex, for: nil do %>
                <%= f.check_box :noindex %>
                <%= Seomore.human_attribute_name(:noindex) %>
            <% end %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.label :nofollow, for: nil do %>
                <%= f.check_box :nofollow %>
                <%= Seomore.human_attribute_name(:nofollow) %>
            <% end %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :canonical, class: 'control-label col-md-2' %>
          <div class="col-md-10">
            <%= f.text_field :canonical, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :author, class: 'control-label col-md-2' %>
          <div class="col-md-10">
            <%= f.text_field :author, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :publisher, class: 'control-label col-md-2' %>
          <div class="col-md-10">
            <%= f.text_field :publisher, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :alternate, class: 'control-label col-md-2' %>
          <div class="col-md-10">
            <%= f.text_field :alternate, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :refresh, class: 'control-label col-md-2' %>
          <div class="col-md-10">
            <%= f.text_field :refresh, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.submit nil, class: 'btn btn-primary' %>
          </div>
        </div>
    <% end %>

<% end %>

app/views/admin/taxonomies/_form.html.erb
<%= form_for([:admin, @taxonomy], html: {class: 'form-horizontal taxonomy', multipart: true}) do |f| %>
<% if @taxonomy.errors.any? %>
<div id="error_explanation" class="panel panel-danger">
  <div class="panel-heading">
    <h2 class="panel-title"><%= pluralize(@taxonomy.errors.count, "error") %> prohibited this taxonomy from
      being saved:</h2>
    </div>

    <div class="panel-body">
      <ul>
        <% @taxonomy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>
    <% if params[:record_type_id].present? %>
        <%= f.hidden_field :record_type_id, value: params[:record_type_id] %>
    <% else %>
  <%= f.hidden_field :record_type_id %>
    <% end %>
  <%= render 'admin/shared/fci/fci_in_model_form', locale: @model=@taxonomy %>

  <div class="form-group">
          <label class="col-md-3 control-label"><%= t(:public) %></label>
          <div class="col-md-9">
             <%= f.check_box :public, class: 'form-control' %>
            <span class="help-block"> <br/> </span>
          </div>
        </div>
  <div class="form-group">
          <label class="col-md-3 control-label"><%= t(:url) %></label>
          <div class="col-md-9">
         <%= f.text_field :url, class: 'form-control' %>
            <span class="help-block"> <%= t('url_help') %> </span>
          </div>
        </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit t('save'), class: 'btn btn-primary' %>
    </div>
  </div>
  <% end %>

app/views/admin/taxonomies/_new_form.html.erb
<%= form_for([:admin, @taxonomy], html: {class: 'form-horizontal taxonomy', multipart: true}) do |f| %>
<% if @taxonomy.errors.any? %>
<div id="error_explanation" class="panel panel-danger">
  <div class="panel-heading">
    <h2 class="panel-title"><%= pluralize(@taxonomy.errors.count, "error") %> prohibited this taxonomy from
      being saved:</h2>
    </div>

    <div class="panel-body">
      <ul>
        <% @taxonomy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>

  <%= f.hidden_field :record_type_id, value: @record_type.id %>

  <%= render 'admin/shared/fci/fci_in_model_form', locale: @model=@record_type %>

  <div class="form-group">
          <label class="col-md-3 control-label"><%= t(:public) %></label>
          <div class="col-md-9">
             <%= f.check_box :public, class: 'form-control' %>
            <span class="help-block"> <br/> </span>
          </div>
        </div>
  <div class="form-group">
          <label class="col-md-3 control-label"><%= t(:url) %></label>
          <div class="col-md-9">
         <%= f.text_field :url, class: 'form-control' %>
            <span class="help-block"> <%= t('url_help') %> </span>
          </div>
        </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit t('save'), class: 'btn btn-primary' %>
    </div>
  </div>
  <% end %>

app/views/admin/taxonomies/_taxonomy.html.erb
<span class="listitem handle"><i class="glyphicon glyphicon-move"></i></span>
<span class="listitem"><a href="/<%= taxonomy.record_type.machine_name %>/<%= taxonomy.url ? taxonomy.url : '-' %>" target="_blank"><%= taxonomy.id %>
  - <%= taxonomy.title %></a></span>
<span class="listitem pub"><% if taxonomy.public %>
<i class="glyphicon glyphicon-ok-circle"></i>
<% else %>
<i class="glyphicon glyphicon-remove-circle"></i>
<% end %>
</span>
<span class="listitem act">
  <%= link_to '', edit_admin_taxonomy_path(taxonomy), class: 'glyphicon glyphicon-pencil' %>
  <%= link_to '', [:admin, taxonomy], method: :delete, data: {confirm: 'Are you sure?'}, class: 'glyphicon glyphicon-remove' %>
</span>

app/views/admin/taxonomies/_taxonomy_list.html.erb
<%= suckerfish taxonomies %>

app/views/admin/taxonomies/edit.html.erb
<%= render 'admin/shared/default/breadcrumbs' %>
<h3 class="page-title">
  <%= t('editing') %> <%= @taxonomy.title %>
  <small><%= @taxonomy.record_type.desc %></small>
</h3>

<div class="well">
<%= render 'form' %>
</div>

app/views/admin/taxonomies/index.html.erb
<%= render 'admin/shared/default/breadcrumbs' %>
<h3 class="page-title">
  <%= t('listing taxonomies') %>
  <small><%= t('taxonomies desc index') %></small>
</h3>

<div class="well">
  
<table class="table table-striped table-bordered table-hover">
  <thead>
  <tr>
    <th>Id</th>
    <th><%= t(:title) %></th>
    <th><%= t(:description) %></th>
    <th><%= t(:action) %></th>
  </tr>
  </thead>

  <tbody>
  <% @record_type_taxonomies.each do |taxonomy_library| %>
      <tr>
        <td><%= taxonomy_library.id %></td>
        <td><%= taxonomy_library.name %></td>
        <td><%= taxonomy_library.desc %></td>
        <td><%= link_to '', admin_taxonomies_list_path(taxonomy_library), class: 'glyphicon glyphicon-list-alt' %>
          <%= link_to '', edit_admin_record_type_path(taxonomy_library), class: 'glyphicon glyphicon-pencil' %>
      </tr>
  <% end %>
  </tbody>
</table>
    </div>

app/views/admin/taxonomies/index.js.erb
$("#sortable-taxonomy").html("<%= escape_javascript(render partial: 'taxonomy_list', locals: { taxonomies: @taxonomies } ) %>");

app/views/admin/taxonomies/list.html.erb
<%= render 'admin/shared/default/breadcrumbs' %>
<h3 class="page-title">
  <%= @record_type.name %>
  <small><%= @record_type.desc %></small>
</h3>

<div class="well">
<div class="portlet box green">
    <div class="portlet-title">
      <div class="caption">
        <i class="fa fa-gift"></i>  <%= t('new taxonomies') %></div>
        <div class="tools">
          <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
        </div>
      </div>
      <div class="portlet-body portlet-collapsed">
      <%= render 'new_form' %>
        </div>
      </div>
  <%= paginate @taxonomies, views_prefix: 'admin' %>
<ul id="sortable-head">
  <li class="clearfix header">
    <span class="listitem sdrag">
       <i class="icon-cursor-move"></i>
    </span>
    <span class="listitem cl">
     <%= t(:name) %>
    </span>
    <span class="listitem pub">
      <%= t(:publiced) %>
    </span>
    <span class="listitem act">
     <%= t(:action) %>
    </span>
  </li>
</ul>

<% if @taxonomies.present? %>

    <ul id="sortable-taxonomy">

      <%= render :partial => 'admin/taxonomies/taxonomy_list', locals: {taxonomies: @taxonomies} %>
    </ul>
<% end %>
</div>

app/views/admin/taxonomies/new.html.erb
<div class="page-header">
  <h1>New taxonomy</h1>
</div>

<%= render 'form' %>

<%= link_to t(:back), admin_taxonomies_path, class: 'btn btn-default' %>

app/views/admin/taxonomies/show.html.erb
<%= link_to t(:edit), edit_admin_taxonomy_path(@taxonomy), class: 'btn btn-default' %>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>action</th>
  </tr>
  </thead>

  <tbody>
  <% @taxonomy.model_relations.each do |mr| %>
      <% @m=mr.model.constantize.find(mr.mid) %>
      <tr>
        <td><%= title(@m) %>
          <% if @m.model_name.name == 'Taxonomy' %>(<%= title(@m.parent) unless @m.parent.nil? %> )
          <% end %></td>

        <td>
          <%= link_to 'Destroy', [:admin, mr], method: :delete %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= search_form_for @search, url: admin_taxonomy_path(@taxonomy) do |f| %>
    <%= f.label 'Type' %>
    <%= f.select :machine_name_cont, options_from_collection_for_select(RecordType.all, :machine_name, :name) %>
    <%= f.submit %>
<% end %>
<%= paginate @types %>
<% @types.each do |type| %>


    <h1><%= type.name %></h1>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>action</th>
      </tr>
      </thead>

      <tbody>
      <% type.model.constantize.where(record_type_id: type.id).each do |model| %>
          <tr>
            <td><%= title(model) %>
              <% if model.model_name.name == 'Taxonomy' %>(<%= title(model.parent) unless model.parent.nil? %> )
              <% end %></td>
            <td><%= form_for([:admin, @mr], remote: true) do |f| %>
                  <%= f.hidden_field :mid, value: model.id %>
                  <%= f.hidden_field :model, value: model.model_name.name %>
                  <%= f.hidden_field :mid_main, value: @taxonomy.id %>
                  <%= f.hidden_field :model_main, value: @taxonomy.model_name.name %>
                  <%= f.hidden_field :record_type, value: model.record_type.machine_name %>
                  <%= f.submit %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>

<%= render 'current_sidebar' %>