config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :messages
  end
  resources :messages
  filter :pagination, :uuid
  filter :locale
  get 'switch_user', to: 'switch_user#set_current_user'
  get 'switch_user/remember_user', to: 'switch_user#remember_user'
  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => '/cable'
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
  root :to => 'records#show', id: '1'
  get 'sheet/search'
  get 'sitemap' => 'sheet#sitemap', format: :xml, as: :sitemap
  get 'robots' => 'sheet#robots', format: :text
  get 'feeds', to: 'sheet#feeds', format: 'rss'
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  get 'admin/record_types/:id/fields' => 'admin/record_types#fields', as: 'admin_record_type_fields'
  get 'admin/records/:id/taxonomypage' => 'admin/records#taxonomypage', as: 'admin_records_taxonomypage'
  get 'admin/records/:id/relationpage' => 'admin/records#relationpage', as: 'admin_records_relationpage'
  get 'admin/blocks/:id/relationpage' => 'admin/blocks#relationpage', as: 'admin_blocks_relationpage'
  get 'admin/taxonomies/list/:record_type_id' => 'admin/taxonomies#list', as: 'admin_taxonomies_list'
  get 'admin/records/list/:record_type_id' => 'admin/records#list', as: 'admin_records_list'
  get 'admin/comments/list/:record_type_id' => 'admin/comments#list', as: 'admin_comments_list'
  get 'admin/transforms/list/:record_type_id' => 'admin/transforms#list', as: 'admin_transforms_list'
  get 'admin/dashboard' => 'admin/statics#dashboard', as: 'admin_dashboard'
  get 'welcome' => 'records/1'
  resources :chat_rooms, only: [:new, :create, :show, :index]

  resources :users, except: [:index]
  resources :profiles
  resources :transforms, only: [:create, :show]
  resources :comments
  resources :flags, only: [:create, :destroy, :index]
  resources :cells
 # resources :records
  resources :users do
    post :unlock, :on => :member
  end

  namespace :admin do
    resources :model_relations
    resources :plugin_managers
    resources :style_images
    resources :fci_dates
    resources :fci_images
    resources :fci_booleans
    resources :fci_decimals
    resources :fci_texts
    resources :fci_strings
    resources :fci_references
    resources :fci_full_texts
    resources :fci_files
    resources :fci_integers
    resources :fci_ratings
    resources :fcis do
      put :sort, on: :collection
    end
    resources :field_customs
    resources :records do
      resources :seomores
    end
    resources :record_types
    resources :taxonomies do
      post :sort, on: :collection
    end
    resources :systems
    resources :seomores
    resources :roles
    resources :users
    resources :menu_items do
      post :sort, on: :collection
    end
    resources :menus
    resources :blocks do
      post :sort, on: :collection
    end
    resources :permissions
    resources :profiles
    resources :cells
    resources :comments
    resources :transforms
    resources :users_roles
    resources :filter_groups
    resources :flags

  end
  #end
  DynamicRouter.load
  #get '*path', to: redirect("/#{I18n.locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.locale}/" }
  #get '', to: redirect("/#{I18n.locale}")


end

app/models/fci_full_text.rb
class FciFullText < ApplicationRecord
  belongs_to :fci
  translates :value
end

app/controllers/admin/fci_full_texts_controller.rb
class Admin::FciFullTextsController < ApplicationController
  before_action :set_fci_full_text, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /admin/fci_full_texts
  # GET /admin/fci_full_texts.json
  def index
    @fci_full_texts = FciFullText.all
  end

  # GET /admin/fci_full_texts/1
  # GET /admin/fci_full_texts/1.json
  def show
  end

  # GET /admin/fci_full_texts/new
  def new
    @fci_full_text = FciFullText.new
  end

  # GET /admin/fci_full_texts/1/edit
  def edit
  end

  # POST /admin/fci_full_texts
  # POST /admin/fci_full_texts.json
  def create
    @fci_full_text = FciFullText.new(fci_full_text_params)

    respond_to do |format|
      if @fci_full_text.save
        format.html { redirect_to [:admin, @fci_full_text], notice: 'Fci full text was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fci_full_text }
      else
        format.html { render action: 'new' }
        format.json { render json: @fci_full_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/fci_full_texts/1
  # PATCH/PUT /admin/fci_full_texts/1.json
  def update
    respond_to do |format|
      if @fci_full_text.update(fci_full_text_params)
        format.html { redirect_to [:admin, @fci_full_text], notice: 'Fci full text was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fci_full_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/fci_full_texts/1
  # DELETE /admin/fci_full_texts/1.json
  def destroy
    @fci_full_text.destroy
    respond_to do |format|
      format.html { redirect_to admin_fci_full_texts_url, notice: 'Fci full text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_fci_full_text
    @fci_full_text = FciFullText.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def fci_full_text_params
    params.require(:fci_full_text).permit(:fci_id, :mid, :model, :value, :format_field)
  end
end

app/helpers/admin/fci_full_texts_helper.rb
module Admin::FciFullTextsHelper
end

app/views/admin/fci_full_texts/_form.html.erb
<%= form_for([:admin, @fci_full_text]) do |f| %>
    <% if @fci_full_text.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@fci_full_text.errors.count, "error") %> prohibited this fci_full_text from being
            saved:</h2>

          <ul>
            <% @fci_full_text.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :fci_id %><br>
      <%= f.text_field :fci_id %>
    </div>
    <div class="field">
      <%= f.label :mid %><br>
      <%= f.number_field :mid %>
    </div>
    <div class="field">
      <%= f.label :model %><br>
      <%= f.text_field :model %>
    </div>
    <div class="field">
      <%= f.label :value %><br>
      <%= f.text_area :value %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/admin/fci_full_texts/_form_field.html.erb
<% fci_full_texts = FciFullText.where(fci_id: @fci.id, model: @model.model_name.human, mid: @model.id) %>
<% if fci_full_texts.empty? %>
            <div class="form-group">
          <label class="col-md-3 control-label"><%= @fci.name %></label>
          <div class="col-md-9">
          <% if @fci.filter? %>
          <%= text_area_tag ":fci_full_text_value"+@fci.machine_name, nil, class: 'form-control', id: 'textareacode', :rows => 20, :cols => 120 %>
          <% else %>
           <%= cktext_area_tag ":fci_full_text_value"+@fci.machine_name, nil, class: 'form-control', :rows => 4, :cols => 120 %>
           <% end %>
            <span class="help-block"> <br/> </span>
          </div>
        </div>
<% else %>
    <% fci_full_texts.each do |text| %>

                    <div class="form-group">
          <label class="col-md-3 control-label"><%= @fci.name %></label>
          <div class="col-md-9">
           <% if @fci.filter? %>
             <%= text_area_tag ":fci_full_text_value"+@fci.machine_name, text.value, autofocus: true, class: 'form-control', id: 'textareacode', :rows => 20, :cols => 120 %>
           <% else %>
           <%= cktext_area_tag ":fci_full_text_value"+@fci.machine_name, text.value, class: 'form-control', :rows => 4, :cols => 120 %>
           <% end %>
         <span class="help-block"> <br/> </span>
          </div>
        </div>
    <% end %>
<% end %>
<script>
    var editor = CodeMirror.fromTextArea($('#textareacode')[0], {
        lineNumbers: true
    });
</script>

app/views/admin/fci_full_texts/edit.html.erb
<h1>Editing fci_full_text</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @fci_full_text] %> |
<%= link_to 'Back', admin_fci_full_texts_path %>

app/views/admin/fci_full_texts/index.html.erb
<h1>Listing fci_full_texts</h1>

<table>
  <thead>
  <tr>
    <th>Fci</th>
    <th>Mid</th>
    <th>Model</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @fci_full_texts.each do |fci_full_text| %>
      <tr>
        <td><%= fci_full_text.fci %></td>
        <td><%= fci_full_text.mid %></td>
        <td><%= fci_full_text.model %></td>
        <td><%= fci_full_text.value %></td>
        <td><%= link_to 'Show', [:admin, fci_full_text] %></td>
        <td><%= link_to 'Edit', edit_admin_fci_full_text_path(fci_full_text) %></td>
        <td><%= link_to 'Destroy', [:admin, fci_full_text], method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fci full text', new_admin_fci_full_text_path %>

app/views/admin/fci_full_texts/new.html.erb
<h1>New fci_full_text</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_fci_full_texts_path %>

app/views/admin/fci_full_texts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fci:</strong>
  <%= @fci_full_text.fci %>
</p>

<p>
  <strong>Mid:</strong>
  <%= @fci_full_text.mid %>
</p>

<p>
  <strong>Model:</strong>
  <%= @fci_full_text.model %>
</p>

<p>
  <strong>Value:</strong>
  <%= @fci_full_text.value %>
</p>

<%= link_to 'Edit', edit_admin_fci_full_text_path(@fci_full_text) %> |
<%= link_to 'Back', admin_fci_full_texts_path %>