config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :messages
  end
  resources :messages
  filter :pagination, :uuid
  filter :locale
  get 'switch_user', to: 'switch_user#set_current_user'
  get 'switch_user/remember_user', to: 'switch_user#remember_user'
  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => '/cable'
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
  root :to => 'records#show', id: '1'
  get 'sheet/search'
  get 'sitemap' => 'sheet#sitemap', format: :xml, as: :sitemap
  get 'robots' => 'sheet#robots', format: :text
  get 'feeds', to: 'sheet#feeds', format: 'rss'
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  get 'admin/record_types/:id/fields' => 'admin/record_types#fields', as: 'admin_record_type_fields'
  get 'admin/records/:id/taxonomypage' => 'admin/records#taxonomypage', as: 'admin_records_taxonomypage'
  get 'admin/records/:id/relationpage' => 'admin/records#relationpage', as: 'admin_records_relationpage'
  get 'admin/blocks/:id/relationpage' => 'admin/blocks#relationpage', as: 'admin_blocks_relationpage'
  get 'admin/taxonomies/list/:record_type_id' => 'admin/taxonomies#list', as: 'admin_taxonomies_list'
  get 'admin/records/list/:record_type_id' => 'admin/records#list', as: 'admin_records_list'
  get 'admin/comments/list/:record_type_id' => 'admin/comments#list', as: 'admin_comments_list'
  get 'admin/transforms/list/:record_type_id' => 'admin/transforms#list', as: 'admin_transforms_list'
  get 'admin/dashboard' => 'admin/statics#dashboard', as: 'admin_dashboard'
  get 'welcome' => 'records/1'
  resources :chat_rooms, only: [:new, :create, :show, :index]

  resources :users, except: [:index]
  resources :profiles
  resources :transforms, only: [:create, :show]
  resources :comments
  resources :flags, only: [:create, :destroy, :index]
  resources :cells
 # resources :records
  resources :users do
    post :unlock, :on => :member
  end

  namespace :admin do
    resources :model_relations
    resources :plugin_managers
    resources :style_images
    resources :fci_dates
    resources :fci_images
    resources :fci_booleans
    resources :fci_decimals
    resources :fci_texts
    resources :fci_strings
    resources :fci_references
    resources :fci_full_texts
    resources :fci_files
    resources :fci_integers
    resources :fci_ratings
    resources :fcis do
      put :sort, on: :collection
    end
    resources :field_customs
    resources :records do
      resources :seomores
    end
    resources :record_types
    resources :taxonomies do
      post :sort, on: :collection
    end
    resources :systems
    resources :seomores
    resources :roles
    resources :users
    resources :menu_items do
      post :sort, on: :collection
    end
    resources :menus
    resources :blocks do
      post :sort, on: :collection
    end
    resources :permissions
    resources :profiles
    resources :cells
    resources :comments
    resources :transforms
    resources :users_roles
    resources :filter_groups
    resources :flags

  end
  #end
  DynamicRouter.load
  #get '*path', to: redirect("/#{I18n.locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.locale}/" }
  #get '', to: redirect("/#{I18n.locale}")


end

app/models/seomore.rb
class Seomore < ApplicationRecord
  has_many :records
  has_many :taxonomies
  translates :title, :keywords, :desc, :canonical,
             :author, :publisher, :alternate, :refresh, :fallbacks_for_empty_translations => true
  default_scope { order("created_at DESC") }
end

app/controllers/admin/seomores_controller.rb
class Admin::SeomoresController < Admin::BaseController
  before_action :set_seomore, only: [:show, :edit, :update, :destroy]
  layout 'admin'
  load_and_authorize_resource
  # GET /admin/seomores
  # GET /admin/seomores.json
  def index
    @seomores = Seomore.all
  end

  # GET /admin/seomores/1
  # GET /admin/seomores/1.json
  def show
  end

  # GET /admin/seomores/new
  def new
    @seomore = Seomore.new
  end

  # GET /admin/seomores/1/edit
  def edit
  end

  # POST /admin/seomores
  # POST /admin/seomores.json
  def create
    @seomore = Seomore.new(seomore_params)

    respond_to do |format|
      if @seomore.save
        format.html { redirect_to admin_seomores_url, notice: 'Seomore was successfully created.' }
        format.json { render action: 'show', status: :created, location: @seomore }
      else
        format.html { render action: 'new' }
        format.json { render json: @seomore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/seomores/1
  # PATCH/PUT /admin/seomores/1.json
  def update
    respond_to do |format|
      if @seomore.update(seomore_params)
        if @seomore.records.first.present?
          redirect_to admin_record_url(@seomore.records.first) and return
        else
          if @seomore.taxonomies.first.present?
            redirect_to admin_taxonomy_url(@seomore.taxonomies.first) and return
          end
        end
        format.html { redirect_to admin_seomores_url, notice: 'Seomore was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @seomore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/seomores/1
  # DELETE /admin/seomores/1.json
  def destroy
    @seomore.destroy
    respond_to do |format|
      format.html { redirect_to admin_seomores_url, notice: 'Seomore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_seomore
    @seomore = Seomore.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def seomore_params
    params.require(:seomore).permit(:title, :keywords, :desc, :noindex, :nofollow, :canonical, :author, :publisher, :alternate, :refresh)
  end
end

app/helpers/admin/seomores_helper.rb
module Admin::SeomoresHelper
end

app/views/admin/seomores/_form.html.erb
<%= form_for([:admin, @seomore], html: {class: 'form-horizontal seomore'}) do |f| %>
    <% if @seomore.errors.any? %>
        <div id="error_explanation" class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title"><%= pluralize(@seomore.errors.count, "error") %> prohibited this seomore from being
              saved:</h2>
          </div>
          <div class="panel-body">
            <ul>
              <% @seomore.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title, class: 'control-label col-md-2' %>
      <div class="col-md-10">
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :keywords, class: 'control-label col-md-2' %>
      <div class="col-md-10">
        <%= f.text_field :keywords, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :desc, class: 'control-label col-md-2' %>
      <div class="col-md-10">
        <%= f.text_area :desc, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <%= f.label :noindex, for: nil do %>
            <%= f.check_box :noindex %>
            <%= Seomore.human_attribute_name(:noindex) %>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <%= f.label :nofollow, for: nil do %>
            <%= f.check_box :nofollow %>
            <%= Seomore.human_attribute_name(:nofollow) %>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :canonical, class: 'control-label col-md-2' %>
      <div class="col-md-10">
        <%= f.text_field :canonical, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :author, class: 'control-label col-md-2' %>
      <div class="col-md-10">
        <%= f.text_field :author, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :publisher, class: 'control-label col-md-2' %>
      <div class="col-md-10">
        <%= f.text_field :publisher, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :alternate, class: 'control-label col-md-2' %>
      <div class="col-md-10">
        <%= f.text_field :alternate, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :refresh, class: 'control-label col-md-2' %>
      <div class="col-md-10">
        <%= f.text_field :refresh, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <%= f.submit nil, class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/admin/seomores/edit.html.erb
<div class="page-header">
  <h1>Editing seomore</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @seomore], class: 'btn btn-default' %>
<%= link_to 'Back', admin_seomores_path, class: 'btn btn-default' %>

app/views/admin/seomores/index.html.erb
<div class="page-header">
  <h1>Listing seomores</h1>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Keywords</th>
    <th>Desc</th>
    <th>Noindex</th>
    <th>Nofollow</th>
    <th>Canonical</th>
    <th>Author</th>
    <th>Publisher</th>
    <th>Alternate</th>
    <th>Refresh</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @seomores.each do |seomore| %>
      <tr>
        <td><%= seomore.title %></td>
        <td><%= seomore.keywords %></td>
        <td><%= seomore.desc %></td>
        <td><%= seomore.noindex %></td>
        <td><%= seomore.nofollow %></td>
        <td><%= seomore.canonical %></td>
        <td><%= seomore.author %></td>
        <td><%= seomore.publisher %></td>
        <td><%= seomore.alternate %></td>
        <td><%= seomore.refresh %></td>
        <td><%= link_to 'Show', [:admin, seomore], class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Edit', edit_admin_seomore_path(seomore), class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Destroy', [:admin, seomore], method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-xs btn-danger' %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seomore', new_admin_seomore_path, class: 'btn btn-primary' %>

app/views/admin/seomores/new.html.erb
<div class="page-header">
  <h1>New seomore</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', admin_seomores_path, class: 'btn btn-default' %>

app/views/admin/seomores/show.html.erb
<p id="notice"><%= notice %></p>

<dl class="dl-horizontal">
  <dt><strong>Title:</strong></dt>
  <dd><%= @seomore.title %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Keywords:</strong></dt>
  <dd><%= @seomore.keywords %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Desc:</strong></dt>
  <dd><%= @seomore.desc %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Noindex:</strong></dt>
  <dd><%= @seomore.noindex %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Nofollow:</strong></dt>
  <dd><%= @seomore.nofollow %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Canonical:</strong></dt>
  <dd><%= @seomore.canonical %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Author:</strong></dt>
  <dd><%= @seomore.author %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Publisher:</strong></dt>
  <dd><%= @seomore.publisher %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Alternate:</strong></dt>
  <dd><%= @seomore.alternate %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Refresh:</strong></dt>
  <dd><%= @seomore.refresh %></dd>
</dl>

<%= link_to 'Edit', edit_admin_seomore_path(@seomore), class: 'btn btn-default' %>
<%= link_to 'Back', admin_seomores_path, class: 'btn btn-default' %>